# Project Name
TARGET = OctavePedal

# Sources
CPP_SOURCES = main.cpp octave.cpp

# Library Locations
LIBDAISY_DIR = ../../../../lib/libdaisy
DAISYSP_DIR = ../../../../lib/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
