# Project Name
TARGET = KinkyBoostClone

# Sources
CPP_SOURCES = Main.cpp KiBoost.cpp

# Library Locations
LIBDAISY_DIR = ../../../../lib/libdaisy
DAISYSP_DIR = ../../../../lib/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
